steps:
  #Build the container image
  - name: 'gcr.io/ardent-course-420113/url-project-image:latest3'
    args: ['deploy']
  #Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'JessCloudDeploymentTrigger'
      - '--image'
      - 'gcr.io/$_PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$_PROJECT_ID/JessCloudDeploymentTrigger:$COMMIT_SHA'
#Checking deployment 2.0.2


